query ownedNfts(
  $after: String
  $includeInLoans: Boolean
  $includeInStash: Boolean
  $standards: [TokenStandardType!]
) {
  ownedNfts: listNftsFromUser(
    after: $after
    withLoans: $includeInLoans
    includeInStash: $includeInStash
    standards: $standards
  ) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        id
        collection {
          id
        }
        tokenId
        price
        priceCurrencyAddress
        activeLoan {
          id
        }
        statistics {
          lastSale {
            order {
              price
              currency {
                ...CurrencyInfo
              }
            }
          }
          topTraitFloorPrice {
            ...CurrencyAmountInfo
          }
        }
      }
    }
  }
}
