query listListings(
  $collections: [Int!]
  $userFilter: UserFilter
  $marketplaceNames: [MarketplaceEnum!]
  $first: Int = 24
  $after: String
) {
  result: listListings(
    collectionIds: $collections
    userFilter: $userFilter
    marketplaceNames: $marketplaceNames
    first: $first
    after: $after
  ) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        id
        marketplaceName
        createdDate
        desiredDuration
        desiredPrincipalAddress
        user {
          walletAddress
        }
        nft {
          id
          tokenId
          collection {
            id
            slug
            contractData {
              contractAddress
            }
          }
        }
      }
    }
  }
}
