query listWithdrawalPositions($poolAddresses: [Address!], $first: Int = 24, $after: String) {
  positions: listWithdrawalPositions(poolAddresses: $poolAddresses, first: $first, after: $after) {
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        ...WithdrawalPositionInfo
      }
    }
  }
}
