export const EFFICIENT_RENEGOTIATION_CODES = {
  REPAYMENT_SIGNATURE: 'EFFICIENT_RENEGOTIATION_REPAYMENT_SIGNATURE',
  EMISSION_SIGNATURE: 'EFFICIENT_RENEGOTIATION_EMISSION_SIGNATURE',
  MIGRATION_SIGNATURE: 'EFFICIENT_RENEGOTIATION_MIGRATION_SIGNATURE',
  MIGRATION_TX: 'EFFICIENT_RENEGOTIATION_MIGRATION_TX',
};
