export const EFFICIENT_RENEGOTIATION_CODES = {
  REPAYMENT_SIGNATURE: 'REPAYMENT_SIGNATURE',
  EMISSION_SIGNATURE: 'EMISSION_SIGNATURE',
  MIGRATION_SIGNATURE: 'MIGRATION_SIGNATURE',
  MIGRATION_TX: 'MIGRATION_TX',
};
